### ISSUE TITLE
Possible bug but more likely my own incompetence

### ISSUE THREAD

**Issue by BigRedScarf** [Craxic/Psiga#1]
So I'm trying to look at some files from Pyre, and after a fair bit of trial and error I still can't figure it out. I looked at some Transistor files about a year ago on another PC, but I forgot how I did it and I can't get it to work now for either game.

I got GTK-Sharp, extracted your zip, and Psiga launches perfectly fine, so that's good, but what I can't figure out is how to actually set the package from the "Select Transistor Package Directory" menu. But when I search through the game folders, I haven't found a single file that wasn't greyed out. I've tried running as admin, I've tried reinstalling GTK, but I can't figure it out.

Out of curiosity I tried using an older version of Psiga to look at Transistor, in case it was a problem specific to Pyre in the new version, but its the same deal there.

Am I just using the interface wrong? Is there some path I need to set somewhere or something? Is the Psiga2 folder supposed to be anywhere in particular? Apologies for the noob questions, but any guidance would be greatly appreciated.

**Comment by Craxic** [comment]
Hey there, sorry about the late response. So, all the files will be greyed out because you're looking for the package **directory** :P. Just pick `steamapps/common/Pyre/Content/Win/Packages` and press OK! You should see all the packages load up and be good to go from there :D

**Comment by BigRedScarf** [comment]
Thanks so much, I feel pretty stupid now haha. :)

**Comment by Craxic** [comment]
Happens to the best of us :D
